version: 2
updates:
# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  labels:
  - dependencies
- package-ecosystem: docker
  directory: "/src/main/docker"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  labels:
  - dependencies
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  labels:
  - dependencies
  groups:
    # See https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
    quarkus-dependencies:
      patterns:
        - "io.quarkus*"
