#The MIT License (MIT)
#
#Copyright (c) 2020 Armel Soro
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

name: Build and Publish Docker Image

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build-test-and-push:

    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve branch or tag name
      id: refvar
      run: echo "::set-output name=gitRefName::${GITHUB_REF#refs/*/}"

    - name: Set up GraalVM
      uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: '20.1.0.java11'

    - name: Install native-image
      run: gu install native-image

    - uses: actions/cache@master
      #Using master because of the multi-paths feature (reportedly only available on master at the moment)
      with:
        path: |
          ~/.gradle/wrapper
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build both native and Docker images
      run: |
        ./gradlew build -x test \
          -Dquarkus.package.type=native \
          -Dquarkus.native.container-build=false \
          -Dquarkus.native.enable-http-url-handler=true \
          -Dquarkus.native.enable-https-url-handler=true \
          -Dquarkus.native.enable-all-security-services=true \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.group=rm3l \
          -Dquarkus.container-image.name=mac-oui \
          -Dquarkus.container-image.tag=latest

    - name: Github Packages - Tag Docker image (latest)
      if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
      run: docker image tag rm3l/mac-oui:latest docker.pkg.github.com/rm3l/mac-oui:latest

    - name: Docker Hub - Tag Docker image (tag)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: docker image tag rm3l/mac-oui:latest rm3l/mac-oui:${{ steps.refvar.outputs.gitRefName }}

    - name: Github Packages - Tag Docker image (tag)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: docker image tag rm3l/mac-oui:latest docker.pkg.github.com/rm3l/mac-oui:${{ steps.refvar.outputs.gitRefName }}

    - name: Login to Docker Hub
      if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Docker Hub - Push Docker image (tag)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: docker image push rm3l/mac-oui:${{ steps.refvar.outputs.gitRefName }}

    - name: Docker Hub - Push Docker image (latest)
      if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
      run: docker image push rm3l/mac-oui:latest

    - name: Login to GitHub Packages Docker Registry
      if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Github Packages - Push Docker image (tag)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: docker push docker.pkg.github.com/rm3l/mac-oui:${{ steps.refvar.outputs.gitRefName }}

    - name: Github Packages - Push Docker image (latest)
      if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
      run: docker push docker.pkg.github.com/rm3l/mac-oui:latest
